# oss_idiary_image.toml: oss 图片存储配置文件

# Service的名字, 必选
Name = "oss_idiary_image"

# oss组件配置
[OSS]
Endpoint = "http://oss-cn-shenzhen.aliyuncs.com"
AccessKeyID = "LTAI5tFEUnHRu5htgFXyKjz7"
AccessKeySecret = "hiXvf2W94smCBv93pjdryOdPRWv0xP"